/** Sort the array a in ascending order using cmp to define the ordering on the
 * elements. */
<T> sort(T[] a, Comparator<T> cmp) {
    ...
    if (cmp.compareTo(a[i], a[j]) > 0) {
        ...
    }
    ...
}
