/** Sort the array a in ascending order using cmp to define the ordering on the
 * elements. */
<T> void sort(T[] a, Comparator<T> cmp) {
    ...
    if (cmp.compare(a[i], a[j]) > 0) {
        ...
    }
    ...
}
